image: node:22.1.0

variables:
  CHROME_BIN: "C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe"

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  before_script:
    - apt-get update
    - wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
    - apt install -y ./google-chrome*.deb;
    - export CHROME_BIN=/usr/bin/google-chrome
  script:
    - npm ci
    - npm run test -- --no-watch --browsers=ChromeHeadlessCI