image: node:22.1.0

build:
  stage: build
  cache:
    paths:
      - node_modules/
  script:
    - npm install --quiet
    - npx nx run skooltrak-app:build:production
  artifacts:
    paths:
      - dist/
  except:
    variables:
      - $CI_COMMIT_MESSAGE =~ /skip-ci/
