image: node:22.1.0

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  image: node:22.1.0
  before_script:
    - apt-get update && apt-get install -y wget gnupg
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
    - apt-get update && apt-get install -y google-chrome-stable
  script:
    - export CHROME_BIN=/usr/bin/google-chrome
    - npm ci
    - npm run test
  artifacts:
    paths:
      - test-results.xml