image: node:22.1.0

variables:
  CHROME_BIN: ""C:\\Program Files\\Google\\Chrome\\Application\\chrome.exe""

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - npm run test
  artifacts:
    paths:
      - test-results.xml