image: node:22.1.0

stages:
  - build
  - test

build:
  stage: build
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  script:
    - npm ci
    - docker run -it --rm node:22.1.0-chrome /bin/bash -c "npm install && ng test"
  artifacts:
    paths:
      - test-results.xml