stages:
  - build

build:
  stage: build
  image: node:22.1.0
  script:
      - npm install -g @angular/cli@17.x.x
      - ng update @angular/core@17 @angular/cli@17
      - npm install
  artifacts:
    paths:
      - dist/