stages:
  - build
  - test

build:
  stage: build
  image: node:22.1.0
  script:
    - npm install -g @angular/cli
    - npm install
    - ng build
  artifacts:
    paths:
      - dist/

unit_tests:
  stage: test
  image: node:22.1.0
  script:
    - npm install -g @angular/cli
    - npm install
    - ng test --watch=false --code-coverage
  artifacts:
    paths:
      - coverage/