stages:
  - build
  - test

build:
  stage: build
  image: node:latest
  script:
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/

test:
  stage: test
  image: node:latest
  script:
    - npm install
    - npm run test