stages:
  - lint
  - test
  - build

lint:
  stage: lint
  image: node:22.1.0
  script:
    - npm install eslint @typescript-eslint/parser @typescript-eslint/eslint-plugin --save-dev
    - npm run lint

test:
  stage: test
  image: node:22.1.0
  script:
    - apt-get update && apt-get install -y wget gnupg
    - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
    - echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google.list
    - apt-get update && apt-get install -y google-chrome-stable
    - npm install @angular/cli
    - ng test --browsers ChromeHeadlessNoSandbox
  variables:
    CHROME_BIN: /usr/bin/google-chrome


build:
  stage: build
  image: node:22.1.0
  script:
    - npm install -g @angular/cli
    - npm install
    - npm run build
  artifacts:
    paths:
      - dist/
